name: Flutter Create App

on:
  workflow_dispatch:

jobs:
  create_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter and Create App
        run: |
          # Install Flutter
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:$GITHUB_WORKSPACE/flutter/bin"

          # Check Flutter works
          flutter doctor

          # Create Flutter project
          flutter create bible_driller_app

          # Copy the created project into the repo root
          cp -r bible_driller_app/* ./
          cp -r bible_driller_app/.* ./ || true  # Copy hidden files too

          # Clean up
          rm -rf bible_driller_app

          # Git commit
          git config --global user.name "Twaddler01"
          git config --global user.email "kenleydad@gmail.com"
          git add .
          git commit -m "Add created Flutter app"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
