name: Flutter Build Debug APK

on:
  workflow_dispatch:

jobs:
  build_debug_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        uses: actions/setup-node@v3
        with:
          fetch-depth: 1  # Only latest commit for speed

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter doctor

      - name: Build debug APK
        working-directory: bible_driller_app
        run: |
          flutter pub get
          flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: bible_driller_app-debug
          path: bible_driller_app/build/app/outputs/flutter-apk/app-debug.apk
