name: Flutter Build Debug APK

on:
  workflow_dispatch:

jobs:
  build_debug_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only latest commit for speed
      - name: Install Flutter manually
        run: |
          # Install Flutter
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:$GITHUB_WORKSPACE/flutter/bin"          
          flutter doctor
      - name: Build debug APK
        working-directory: bible_driller_app
        run: |
          flutter pub get
          flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bible_driller_app-debug
          path: bible_driller_app/build/app/outputs/flutter-apk/app-debug.apk
