name: Build Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.3.0  # Use a specific and tested version
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK in Debug mode
        run: flutter build apk --debug

      - name: Upload Debug APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
