name: Flutter Create App

on:
  workflow_dispatch:

jobs:
  create_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter and Create App
        run: |
          # Install Flutter
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:$GITHUB_WORKSPACE/flutter/bin"

          # Check Flutter works
          flutter doctor

          # Create Flutter project
          flutter create bible_driller_app

          # Git commit
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bible_driller_app
          git commit -m "Add created Flutter app"
          git push
